#!/bin/sh
yum -y update
yum install http://plain.resources.ovirt.org/pub/yum-repo/ovirt-release35.rpm
yum -y install ovirt-engine
engine-setup


# ISO upload from ovirt-engine
engine-iso-uploader -u nfs.ipvbd.com --nfs-server=nfs.ipvbd.com:/srv/ovirt/iso/bce5ee08-df87-457e-8145-dbe35619a497/images/11111111-1111-1111-1111-111111111111 upload  /CentOS-7-x86_64-Minimal-1503-01.iso
# SPICE Install
yum install spice-xpi
