#!/bin/sh
# Architechture
DNS: ns1.ipvbd.com 172.16.20.9
Ovirt-Engine: ovirtengine.ipvbd.com 172.16.20.24
Ovirt-Node(KVm): ovirtnode.ipvbd.com 172.16.20.22
NFS: nfs.ipvbd.com 172.16.20.23
Client(Desktop): client.ipvbd.com 172.16.20.62

# Install Ovirt Engine
yum -y update
#yum install http://plain.resources.ovirt.org/pub/yum-repo/ovirt-release35.rpm
yum install http://plain.resources.ovirt.org/pub/yum-repo/ovirt-release36.rpm
yum -y install ovirt-engine
engine-setup

# Ovirt Node Install 
yum -y install qemu-kvm libvirt virt-install bridge-utils
systemctl start libvirtd 
systemctl enable libvirtd 
yum -y localinstall http://plain.resources.ovirt.org/pub/yum-repo/ovirt-release36.rpm
yum -y install vdsm
# Install spice on ovirtnode. Normally it installed with kvm as a dependancy
yum -y install spice-server spice-protocol 

# NFS Server Install
 vi /etc/sysconfig/nfs
 # add to the end
NFS4_SUPPORT="no"
#
mkdir /var/lib/libvirt/images
mkdir /var/lib/libvirt/iso
mkdir /var/lib/libvirt/export 
#chown 36:36 /var/lib/libvirt/images
chown vdsm:kvm /var/lib/libvirt/images
chown vdsm:kvm /var/lib/libvirt/iso
chown vdsm:kvm /var/lib/libvirt/export
# Export NFS Share
vi /etc/exports.d/ovirt-engine-iso-domain.exports
/var/lib/libvirt/iso    172.16.20.0/24(rw)
/var/lib/libvirt/images   172.16.20.0/24(rw)
/var/lib/libvirt/export   172.16.20.0/24(rw)
systemctl enable rpc-statd nfs-server 
systemctl restart rpc-statd nfs-server 

# ISO upload from ovirt-engine
engine-iso-uploader -u nfs.ipvbd.com --nfs-server=nfs.ipvbd.com:/srv/ovirt/iso/bce5ee08-df87-457e-8145-dbe35619a497/images/11111111-1111-1111-1111-111111111111 upload  /CentOS-7-x86_64-Minimal-1503-01.iso
# SPICE Install on Client Computer
yum -y install firefox spice-xpi
# or
yum install spice-xpi
#
#
# Debugging steps  // NOT NECESSARY HERER
yum install ovirt-engine-webadmin-portal-debuginfo ovirt-engine-userportal-debuginfo


