#!/bin/sh
# Architechture
DNS: ns1.ipvbd.com 172.16.20.9
Ovirt-Engine: ovirtengine.ipvbd.com 172.16.20.24
Ovirt-Node(KVm): ovirtnode.ipvbd.com 172.16.20.22
NFS: nfs.ipvbd.com 172.16.20.23

# Install Ovirt Engine
yum -y update
#yum install http://plain.resources.ovirt.org/pub/yum-repo/ovirt-release35.rpm
yum install http://plain.resources.ovirt.org/pub/yum-repo/ovirt-release36.rpm
yum -y install ovirt-engine
engine-setup

# Ovirt Node Install 
yum -y localinstall http://plain.resources.ovirt.org/pub/yum-repo/ovirt-release36.rpm
yum -y install vdsm

# NFS Server Install
 vi /etc/sysconfig/nfs
 # add to the end
NFS4_SUPPORT="no"
#
mkdir /var/lib/exports/data
mkdir /var/lib/exports/iso
mkdir /var/lib/exports/export 
#chown 36:36 /var/lib/exports/data
chown vdsm:kvm /var/lib/exports/data
chown vdsm:kvm /var/lib/exports/iso
chown vdsm:kvm /var/lib/exports/export

vi /etc/exports.d/ovirt-engine-iso-domain.exports
/var/lib/exports/iso    172.16.20.0/24(rw)
/var/lib/exports/data   172.16.20.0/24(rw)
/var/lib/exports/export   172.16.20.0/24(rw)
systemctl restart rpc-statd nfs-server 

# ISO upload from ovirt-engine
engine-iso-uploader -u nfs.ipvbd.com --nfs-server=nfs.ipvbd.com:/srv/ovirt/iso/bce5ee08-df87-457e-8145-dbe35619a497/images/11111111-1111-1111-1111-111111111111 upload  /CentOS-7-x86_64-Minimal-1503-01.iso
# SPICE Install
yum install spice-xpi
